### ISSUE TITLE
Bind truly-optional nullable properties

### ISSUE THREAD

**Issue by JakeWharton** [xenomachina/kotlin-argparser#11]
I've been using sentinel values and `default()` to accomplish this, but it's gets awkward when using custom types. I would really like something like `optional()` which turned the property into a having a nullable type.

**Comment by JakeWharton** [comment]
I'd also be interested in the ability to specify a nullable default. For example, in the case of this file we default to a path specified by a system property which may not be present.
```kotlin
val path by parser.storing("The path", ::File)
    .optional()
    .default(System.env("THE_PATH")?.let(::File))
```

**Comment by xenomachina** [comment]
Does something like this do what you want?

    val path by parser.storing<File?>("The path", ::File)
            .default(System.getenv("THE_PATH")?.let(::File))

It would be nice if a nullable default made the Delegate's type nullable. Actually, it would be nice if in in general setting the default could "relax" the type of the delegate (that is, make the Delegate<T> into a Delegate<S> where S is a super-type of T and the default value).

I'm currently investigating to see if there's a way to do this in Kotlin's type system.

**Comment by JakeWharton** [comment]
Hmm I was under the impression that the internals required a non-null value but I might have been mistaken. I will give your suggestion a try today.

**Comment by xenomachina** [comment]
If they do, that is probably a bug. I jumped through some hoops to distinguish between "not set" and "set to null".

**Comment by JakeWharton** [comment]
Ok so it works for `File?` when explicitly specified and which allows the use of `default(null)` (or some nullable thing).

It's a bit awkward for nullable string arguments though as you have to pass an identity function because the non-transformer overload doesn't have a generic parameter.
```kotlin
val title by parser.storing<String?>("Execution title", { this }).default(null)
```

**Comment by xenomachina** [comment]
That's a good point. Commit 1bc14745edb070bffd8e076fd67b6eef52631bd5 changes the way `default` works that fixes this. It makes `default` into an extension method, and so now the default value can be nullable, actually null, or even some other type. The resulting property will have the most specific superclass. In the case of starting with a `Delegate<String>`, you'll get a `Delegate<String?>` if the default is `null` or `String?`, regardless of which factory method created the original.

It's a somewhat backwards incompatible change, as `Delegate` is now an abstract class instead of an interface. Really, I probably should have done that from the beginning, as I never meant for people to be able to create their own `Delegate` implementations.

**Comment by xenomachina** [comment]
I'm going to close this as I think 1bc14745edb070bffd8e076fd67b6eef52631bd5 should solve the root issue.
