### ISSUE TITLE
.addValidator after .default removes default setting

### ISSUE THREAD

**Issue by PvdBerg1998** [xenomachina/kotlin-argparser#18]
The following code
```Kotlin
private val x by parser.storing(
		"-x",
		help = "",
		transform = String::toInt
).addValidator {
	// Validate here
}.default(0)
```
receives the default value of 0 and gets labeled as optional, while
```Kotlin
private val x by parser.storing(
		"-x",
		help = "",
		transform = String::toInt
).default(0).addValidator {
	// Validate here
}
```
does not, and gets labeled as required parameter.

**Comment by PvdBerg1998** [comment]
Note that the first snippet produces a NPE when the optional property gets left out.

**Comment by xenomachina** [comment]
Thanks for reporting this issue. I'm working on a fix and should have something ready shortly.

**Comment by xenomachina** [comment]
Ok, I have released a fix for this. The second test case, `.default(...).addValidator(...)` now works correctly.

The first test case, `.addValidator(...).default(...)`, will now throw an `IllegalStateException`, as this is a potentially unsafe operation, since .default can actually change the type (for example, making it nullable, or by making it a supertype), and then there's no way to pass the default value to the validator.

I'm debating whether to make it possible to add  a validator before a default, and simply have the validator not called when the default is used. This is potentially surprising behavior.

**Comment by PvdBerg1998** [comment]
Nice, thanks for the support.
