### ISSUE TITLE
Usable example?

### ISSUE THREAD

**Issue by dsully** [xenomachina/kotlin-argparser#21]
Can you add a full, usable example to either the docs or the repo?

ie: something that is a complete program that can be run.

Thanks

**Comment by xenomachina** [comment]
This is a good idea.

I probably won't have a chance to put up a full example for a couple of days, but Googling for "site:github.com kotlin-argparser -inurl:kotlin-argparser" turns up a few examples.

**Comment by aneksamun** [comment]
+1: Finding help no working for me

**Comment by lucasvalenteds** [comment]
@dsully @aneksamun Check the pull request #28 in case you still need a working sample.

**Comment by asarkar** [comment]
+1 for example. Let's consider the README:
```
class MyArgs(parser: ArgParser) {
    val verbose by parser.flagging("-v", "--verbose",
                                   help = "enable verbose mode")

    val name by parser.storing("-w", "--widget-name",
                               help = "name of the widget")

    val size by parser.storing("-s", "--size",
                               help = "size of the plumbus") { toInt() }
}
```

Questions I've as soon as I see this:
1. How do I instantiate an `ArgParser`?
2. How do I provide default values.
3. Great, I've made a class `MyArgs`. I still don't see how to use it for parsing args array.
4. No, I don't want to dig through unit tests and source code. You're claiming easy-to-use.

See, why examples are great?

**Comment by nbhanji** [comment]
I have searched google for examples -- cannot find.  Declaring a class MyArgs and no underpinning on how to use in main part, that is kind of losing the point of making it easy.  Can you please provide at least general or even getting help to print on screen.

Thanks.

**Comment by xenomachina** [comment]
Thanks for your patience, everyone. I agreed from the start that a complete example would be great, but didn't have the time to put one together earlier, and I wasn't sure how to best "package" it.

I finally got around to making one. You can find it here: [kotlin-argparser-example](https://github.com/xenomachina/kotlin-argparser-example)

It's in a separate repo because I didn't want it to rely on any complex gradle magic, and I wanted it to be an easy starting point for someone to just copy the entire thing and start working, if they so choose. (The latter is also why it uses Unlicense.) I've linked to it from the readme.

I hope you find it useful.
