### ISSUE TITLE
Provide validation option for positional arguments

### ISSUE THREAD

**Issue by asarkar** [xenomachina/kotlin-argparser#43]
It appears that there is no support for validating positional arguments.

**Comment by xenomachina** [comment]
You can use `addValidator` with a positional just as you can with an option. See `PositionalAddValidatorTest` and `PositionalListAddValidatorTest`.

**Comment by asarkar** [comment]
But documentation? If your response is going to be "why, it's open source", let me know ahead of time. :)

**Comment by xenomachina** [comment]
I referenced the tests because it was unclear whether you were saying you didn't know how to do it, or that it didn't work. The README tries to be concise, so it cannot have an example of every permutation imaginable. The tests are sometimes useful for finding cases that aren't spelled out in the README.

For complete reference documentation you can use the KDocs, which would show that `positional` returns a `DelegateProvider`, and that `DelegateProvider` has an `addValidator` method.

That said, the README actually does touch on this specific issue:

> Each option and **positional argument is declared as a property that delegates** through a
delegate factory method on an instance of `ArgParser`.

and later:

> The delegates returned by **any** of these methods also have a few methods for setting optional attributes

(emphasis added) It then goes on to describe `addValidator` as one of the methods for modifying delegates.

If you think this could be worded more clearly I'd be happy to look at a PR.
