### ISSUE TITLE
Make mainBody inline

### ISSUE THREAD

**Issue by pcoltau** [xenomachina/kotlin-argparser#46]
If the `mainBody` function was inline, it would be possible to return from the `body` function and then end the program execution.

**Comment by xenomachina** [comment]
Good idea!
 
One gotcha with this: if you only `return` from (an inline version of) `mainBody`'s lambda sometimes, it's fine, but if you do it on every code path you start getting errors like:

```
Kotlin: 'Nothing' return type needs to be specified explicitly
Kotlin: This function must return a value of type Nothing
```

This is because returning from `main` in every code path of `mainBody` means that `mainBody`'s return type is now `Nothing` (as is always exits prematurely), and the type of `main` is the same as `mainBody` in the typical usage.

A workaround (which also works right now, BTW) is to use a qualified `return`:

    return@mainBody

This returns from `mainBody`, rather than from `main`, but  in the typical usage that's pretty much the same thing.

Another work around is to write something like this:

```kotlin
fun main(args: Array<String>) {
    mainBody {
        ...
        return
    }
}
```

instead of:

```kotlin
fun main(args: Array<String>) = mainBody {
        ...
        return
    }
```

This decouples the type from `mainBody`'s lambda from `main`, so Kotlin is happy.

**Comment by pcoltau** [comment]
That you for that detailed answer! 

I think using `return@mainBody` is a fine solution.
